FROM quay.io/stefanprodan/kube-metrics-adapter:master-478c97d

RUN apk info -a musl
RUN apk update
RUN apk upgrade
#RUN apk add --upgrade musl-1.1.19-r11
#RUN apk add musl-1.1.19-r11
RUN apk info -a musl